---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table6maansibletest
        location: southindia
        tags:
           testing: testing
           delete: never
