---
- hosts: localhost
  connection: local
  vars:
    group: table6mawebapprg
    webapp_name: table6mawebapp
    location: southindia
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ group  }}"
      location: "{{ location  }}"
  - name: Create Web app
    azure_rm_webapp:
      resource_group: "{{ group }}"
      name: "{{ webapp_name }}"
      plan:
        resource_group: "{{ group }}"
        name: table6maplan
        is_linux: true
        sku: S1
        number_of_workers: 1
      frameworks:
        - name: "java"
          version: "8"
          settings:
            java_container: tomcat
            java_container_version: 8.5
